### PR TITLE
Read a contract as `State`

### LINKED ISSUE #49: Fetch contract data via the SDK
Programmatically access a contract's data, and interpret it as our internal type `State`, which can be written out to ITF and read by the monitor executor.

### PR DESCRIPTION
**Pull request by Kukovec**
closes #49 

Adds the following:
 - Methods to submit an RPC request for a subset of contract data fields
 - Response validation
 - XDR -> `State` conversion
 - Test implementing the [tutorial](https://developers.stellar.org/network/soroban-rpc/api-reference/methods/getLedgerEntries)

### CODE REVIEW

**Review by konnov — APPROVED** [review]
I have only a few small comments. Apart from that, the code seems to be doing what it is supposed to do. It should be good enough for MVP. Let's merge it

**Comment by konnov** [comment]
The test is failing though. @Kukovec do you know what is happening?

**Comment by Kukovec** [comment]
> The test is failing though. @Kukovec do you know what is happening?

No clue, it's not the actual tests in the code, but the solarkraft build itself. The error messages are pretty unhelpful. Cannot reproduce locally.

**Comment by konnov** [comment]
> > The test is failing though. @Kukovec do you know what is happening?
> 
> No clue, it's not the actual tests in the code, but the solarkraft build itself. The error messages are pretty unhelpful (`"Cannot find type definition file for 'urijs'."`). Cannot reproduce locally.

it looks like you do not have `@types/urijs` maybe?

**Comment by konnov** [comment]
Looking at the reported error, I had to fix the missing dependency:

```
npm i @types/urijs
```

After doing that, I am getting exactly the same error message, as Github is reporting.

**Comment by konnov** [comment]
I guess, the issue is that we are compiling the project with nodejs, whereas `stellar-sdk` expect some types that are available only in a browser.

**Comment by konnov** [comment]
There were several reasons for the test not going through:

 1. The dependency `@types/urijs` missing.
 2. Another dependency `eventsource` mentioned in the failing `node_modules/@stellar/stellar-sdk/types/dom-monkeypatch.d.ts`.
 3. Finally, `tsc` had collisions on `Event`. I could not figure out how to fix that but by setting `skipLibCheck` to `true` in `tsconfig.json`.

**Comment by konnov** [comment]
Since the test is passing now, I will merge the PR, so we are not blocked with further development

**Pull request merged**
