### PR TITLE
add a fetcher test

### PR DESCRIPTION
**Pull request by konnov**
As promised, here is an e2e test for the fetcher

### CODE REVIEW

**Comment by Kukovec** [comment]
`npm run e2e` fails for me with:
```
  1) fetch
       fetches transactions:

      AssertionError [ERR_ASSERTION]: Non-empty queue on spawn exit.
[wait] Target contract: CC22QGTOUMERDNIYN7TPNX3V6EMPHQXVSRR3XY56EADF7YTFISD2ROND
[wait] Fetching the ledger for 1638368
[wait] + save: 1638383
      + expected - actual

      -[
      -  "[wait] Target contract: CC22QGTOUMERDNIYN7TPNX3V6EMPHQXVSRR3XY56EADF7YTFISD2ROND"
      -  "[wait] Fetching the ledger for 1638368"
      -  "[wait] + save: 1638383"
      -]
      +[]
```

**Comment by Kukovec** [comment]
> > `npm run e2e` fails for me with:
> > ```
> >   1) fetch
> >        fetches transactions:
> > 
> >       AssertionError [ERR_ASSERTION]: Non-empty queue on spawn exit.
> > [wait] Target contract: CC22QGTOUMERDNIYN7TPNX3V6EMPHQXVSRR3XY56EADF7YTFISD2ROND
> > [wait] Fetching the ledger for 1638368
> > [wait] + save: 1638383
> >       + expected - actual
> > 
> >       -[
> >       -  "[wait] Target contract: CC22QGTOUMERDNIYN7TPNX3V6EMPHQXVSRR3XY56EADF7YTFISD2ROND"
> >       -  "[wait] Fetching the ledger for 1638368"
> >       -  "[wait] + save: 1638383"
> >       -]
> >       +[]
> > ```
> 
> Can you run manually what the test is doing and see what happens?
> 
> ```
> solarkraft fetch --rpc https://horizon-testnet.stellar.org --id CC22QGTOUMERDNIYN7TPNX3V6EMPHQXVSRR3XY56EADF7YTFISD2ROND --height 1638368 --timeout 10
> ```

**Comment by Kukovec** [comment]
> So it did work as expected. Are you sure you ran the test with an up-to-date version of `npm run compile`?

I tried it 5s ago, `install -> compile -> run e2e`:
```
  fetch
    ✔ fetches transactions (10919ms)

  verify
    ✔ errors on missing file (128ms)
    ✔ errors on no monitors given (103ms)
    1) reports success on okay monitor1
    2) reports success on okay monitor2
    3) reports success on two okay monitors
    4) reports failure on deadlocking monitor
    5) reports failure on deadlocking monitor, if another succeeding monitor is present


  3 passing (12s)
  5 failing
```

**Review by Kukovec — APPROVED** [review]

**Comment by thpani** [comment]
> > So it did work as expected. Are you sure you ran the test with an up-to-date version of `npm run compile`?
> 
> I tried it 5s ago, `install -> run compile -> run e2e`:
> 
> ```
>   fetch
>     ✔ fetches transactions (10919ms)
> 
>   verify
>     ✔ errors on missing file (128ms)
>     ✔ errors on no monitors given (103ms)
>     1) reports success on okay monitor1
>     2) reports success on okay monitor2
>     3) reports success on two okay monitors
>     4) reports failure on deadlocking monitor
>     5) reports failure on deadlocking monitor, if another succeeding monitor is present
> 
> 
>   3 passing (12s)
>   5 failing
> ```

Like really, it just looks as if it can't run Apalache for some reason.

**Pull request merged**
